### ISSUE TITLE
Couldn't find 'checkpoint' file

### ISSUE THREAD

**Issue by elricwan** [LydiaXiaohongLi/Albert_Finetune_with_Pretrain_on_Custom_Corpus#2]
When I run the estimator.train(input_fn=train_input_fn, max_steps=num_train_steps) for the final step, I receive the error that "Couldn't find 'checkpoint' file". And I do not find the checkpoint file here too, how to generate by myself?

**Comment by LydiaXiaohongLi** [comment]
Hi,
Have you run the previous steps of build vocab, create pretrain files, pretrain models first before the fine tuning job? Following these steps, it will generate the model and model checkpoint file. Alternatively if you wan directly finetune on pretrained albert english models, you can download the model from albert repo and modify accordingly (i will publish this part in seperate repo soon).

**Comment by elricwan** [comment]
Hi
Thanks for the quick response, I didn't run the previous steps, the notebook is easier for me to understand and manage. I would do this now, besides, I am looking forward to the new part you are planning to do.
Best.
