### ISSUE TITLE
checkpoint

### ISSUE THREAD

**Issue by elricwan** [LydiaXiaohongLi/Albert_Finetune_with_Pretrain_on_Custom_Corpus#3]
Hi 

I download the data, but I am not sure where to put it as checkpoint file. Do you mind make a Github version with complete running environment with Jupyter? Thank you!

**Comment by LydiaXiaohongLi** [comment]
@xwan6 , there u go, please refer to the colab notebook Albert_Finetune_with_Pretrain_on_Custom_Corpus_ToyModel.ipynb in this repo, for E2E steps for the toy model. It can fit in CPU.

**Comment by elricwan** [comment]
I see, thank you so much!

Best
Xiangpeng
